[en]
  languageName = ":us:"
  [en.params]
    description = "Tobias Lindberg's website"
    info = "Cloud Infrastructure Engineer | Father | Tesla enthusiast | Creator of TibiaData"
    footercontent = "This page is hosted on GitHub Pages"
    images = ["images/open-graph-image-en.png"]

[se]
  languageName = ":sweden:"
  [se.params]
    description = "Tobias Lindberg's hemsida"
    info = "Cloud Infrastructure Engineer | Far | Tesla entusiast | Skapare av TibiaData"
    footercontent = "Denna sida tillhandahålls på GitHub Pages"
    images = ["images/open-graph-image-se.png"]

[de]
  languageName = ":de:"
  [de.params]
    description = "Tobias Lindberg's webseite"
    info = "Cloud Infrastructure Engineer | Vater | Tesla-Enthusiast | Schöpfer von TibiaData"
    footercontent = "Diese Seite wird auf GitHub Pages gehostet"
    images = ["images/open-graph-image-de.png"]
